### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by doudoucao** [DUT-LiuYang/Aspect-Sentiment-Analysis#2]
请问您实验所用的数据是SemEval 2014的吗？

**Comment by DUT-LiuYang** [comment]
是的

**Comment by doudoucao** [comment]
但是数量怎么好像不一样呢

**Comment by DUT-LiuYang** [comment]
我确实和我之前的某几篇论文数量差了几个，而他们之间也不是完全一致。我是从评测网站下载的v2版。这个就请相信自己的判断和调查吧。我论文里写的是我实验的实例数量。

**Comment by HaimianYu** [comment]
但是您论文里面写的数据集的统计和您发出来的数据集的数量也差的有点多呀。restaurant的测试集您论文里面写的是1120，但是您发出来的只有800+，感觉差的有点多啊，因为我最近也在做这个，但是我的restaurant里面的测试集就刚刚有1120

**Comment by DUT-LiuYang** [comment]
> 但是您论文里面写的数据集的统计和您发出来的数据集的数量也差的有点多呀。restaurant的测试集您论文里面写的是1120，但是您发出来的只有800+，感觉差的有点多啊，因为我最近也在做这个，但是我的restaurant里面的测试集就刚刚有1120

论文里写的是实例个数，即需要测试的aspect的个数。而您说的800+，是句子的个数，而一个句子可能存在多个aspect，一个aspect与其所在的句子作为一条实例。您看的那个文件，是分好词的句子个数，没有经过复制。关于实例数量的问题，您可以看名字为aspect_token的另一个文件。祝好。

**Comment by HaimianYu** [comment]
> > 但是您论文里面写的数据集的统计和您发出来的数据集的数量也差的有点多呀。restaurant的测试集您论文里面写的是1120，但是您发出来的只有800+，感觉差的有点多啊，因为我最近也在做这个，但是我的restaurant里面的测试集就刚刚有1120
> 
> 论文里写的是实例个数，即需要测试的aspect的个数。而您说的800+，是句子的个数，而一个句子可能存在多个aspect，一个aspect与其所在的句子作为一条实例。您看的那个文件，是分好词的句子个数，没有经过复制。关于实例数量的问题，您可以看名字为aspect_token的另一个文件。祝好。

请问您测试数据集用的是哪一个呢，v2版的好像只有训练数据集，没有测试数据集

**Comment by HaimianYu** [comment]
> > 但是您论文里面写的数据集的统计和您发出来的数据集的数量也差的有点多呀.restaurant的测试集您论文里面写的是1120，但是您发出来的只有800+，感觉差的有点多啊，因为我最近也在做这个，但是我的餐厅里面的测试集就刚刚有1120
> 
> 论文里写的是实例个数，即需要测试的方面的个数。而您说的800+，是句子的个数，而一个句子可能存在多个方面，一个方面与其所在的句子作为一条实例。您看的那个文件，是分好词的句子个数，没有经过复制。关于实例数量的问题，您可以看名字为aspect_token的另一个文件。祝好。

或者能不能把您XML处理后的训练、测试数据集发出来一下呢

**Comment by DUT-LiuYang** [comment]
> 
> 
> > > 但是您论文里面写的数据集的统计和您发出来的数据集的数量也差的有点多呀.restaurant的测试集您论文里面写的是1120，但是您发出来的只有800+，感觉差的有点多啊，因为我最近也在做这个，但是我的餐厅里面的测试集就刚刚有1120
> > 
> > 
> > 论文里写的是实例个数，即需要测试的方面的个数。而您说的800+，是句子的个数，而一个句子可能存在多个方面，一个方面与其所在的句子作为一条实例。您看的那个文件，是分好词的句子个数，没有经过复制。关于实例数量的问题，您可以看名字为aspect_token的另一个文件。祝好。
> 
> 或者能不能把您XML处理后的训练、测试数据集发出来一下呢

测试集没有v2版，就用的正常的。处理后的训练测试数据就在data文件夹中。label跑一下程序就能生成出来。
