### ISSUE TITLE
position embedding这部分代码是什么流程呢

### ISSUE THREAD

**Issue by willemNLP** [DUT-LiuYang/Aspect-Sentiment-Analysis#3]

**Comment by willemNLP** [comment]
文章position给出的公式这里是怎么利用的呢

**Comment by DUT-LiuYang** [comment]
根据每个单词对应候选目标的位置，映射到一个随机初始化的位置权重矩阵。

**Comment by willemNLP** [comment]
位置只是一个固定的数值，怎么映射成一个多维矩阵的呢？具体代码在哪一段呢，这代码有点乱

**Comment by DUT-LiuYang** [comment]
有点乱…😂

1.   每个单词的位置如何映射成embedding：model里的embedding层
2.   每个实例的位置信息输入怎么得到：example reader里

**Comment by willemNLP** [comment]
请问，论文中 attention  可视化怎么做出来的

**Comment by DUT-LiuYang** [comment]
输出中间层的结果(read model.py)，用别的软件画的。
