### ISSUE TITLE
运行Main.py时报错

### ISSUE THREAD

**Issue by ghost** [DUT-LiuYang/Aspect-Sentiment-Analysis#5]
你好，请问一下这个报错应该怎么改？
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 78, 300), (None, 82, 600)]

**Comment by DUT-LiuYang** [comment]
两个语料的最大句子长度设置的不一样，一个是78，一个是82，你看下，保证concatenate之前第二维一样就行。
